-- Create READ_ONLY_ANALYST role with limited privileges
CREATE ROLE READ_ONLY_ANALYST;

-- Grant only SELECT and CREATE VIEW privileges
GRANT CREATE SESSION TO READ_ONLY_ANALYST;
GRANT CREATE VIEW TO READ_ONLY_ANALYST;
GRANT SELECT ANY TABLE TO READ_ONLY_ANALYST;

-- Remove SUPER_USER role from AMILLAN and CRISAGUILA
REVOKE SUPER_USER FROM AMILLAN;
REVOKE SUPER_USER FROM CRISAGUILA;

-- Grant new READ_ONLY_ANALYST role to AMILLAN and CRISAGUILA
GRANT READ_ONLY_ANALYST TO AMILLAN;
GRANT READ_ONLY_ANALYST TO CRISAGUILA;

-- Set as default role for both users
ALTER USER AMILLAN DEFAULT ROLE READ_ONLY_ANALYST;
ALTER USER CRISAGUILA DEFAULT ROLE READ_ONLY_ANALYST;

-- Verify the changes
SELECT grantee, granted_role FROM dba_role_privs WHERE grantee IN ('AMILLAN', 'CRISAGUILA');
SELECT role, privilege FROM role_sys_privs WHERE role = 'READ_ONLY_ANALYST';

