------------------------------------------------------------------------
-- DATABASE SCHEMA CREATION SCRIPT
------------------------------------------------------------------------
-- Start transaction
SET AUTOCOMMIT OFF;

-- LOCATION RELATED TABLES
CREATE TABLE REGIONES (
  REGION_ID SMALLINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  REGION_NOMBRE varchar(64) NOT NULL,
  REGION_ORDINAL varchar(4) NOT NULL,
  CONSTRAINT UK_REGIONES UNIQUE (REGION_NOMBRE, REGION_ORDINAL)
);


CREATE TABLE PROVINCIAS (
  PROVINCIA_ID SMALLINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  PROVINCIA_NOMBRE varchar(64) NOT NULL,
  REGION_ID SMALLINT NOT NULL,
  CONSTRAINT UK_PROVINCIAS UNIQUE (PROVINCIA_NOMBRE, REGION_ID)
);

CREATE TABLE COMUNAS (
  COMUNA_ID SMALLINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  COMUNA_NOMBRE varchar(64) NOT NULL,
  PROVINCIA_ID SMALLINT NOT NULL,
  REGION_ID SMALLINT NOT NULL,
  CONSTRAINT UK_COMUNAS UNIQUE (COMUNA_NOMBRE, PROVINCIA_ID, REGION_ID)
);


-- DEGREE PROGRAM RELATED TABLES
CREATE TABLE TIPOS_EDUCACION (
    TIPO_EDUCACION_ID SMALLINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TIPO_EDUCACION_NOMBRE VARCHAR2(30) NOT NULL,
    TIPO_EDUCACION_DESCRIPCION VARCHAR2(100),
    CONSTRAINT UK_TIPOS_EDUCACION UNIQUE (TIPO_EDUCACION_NOMBRE)
);

CREATE TABLE NIVELES_FORMACION (
    NIVEL_FORMACION_ID SMALLINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NIVEL_FORMACION_NOMBRE VARCHAR2(20) NOT NULL,
    NIVEL_FORMACION_DESCRIPCION VARCHAR2(100),
    CONSTRAINT UK_NIVELES_FORMACION UNIQUE (NIVEL_FORMACION_NOMBRE)
);

CREATE TABLE NIVELES_CARRERA (
    NIVEL_CARRERA_ID SMALLINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TIPO_EDUCACION_ID SMALLINT NOT NULL,
    NIVEL_FORMACION_ID SMALLINT NOT NULL,
    NIVEL_CARRERA_DESCRIPCION VARCHAR2(100),
    CONSTRAINT UK_NIVELES_CARRERA UNIQUE (TIPO_EDUCACION_ID, NIVEL_FORMACION_ID)
);

CREATE TABLE AREAS_CONOCIMIENTO (
    AREA_CONOCIMIENTO_ID SMALLINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    AREA_CONOCIMIENTO_NOMBRE VARCHAR2(100) NOT NULL,
    AREA_CONOCIMIENTO_DESCRIPCION VARCHAR2(500),
    CONSTRAINT UK_AREAS_CONOCIMIENTO UNIQUE (AREA_CONOCIMIENTO_NOMBRE)
);

CREATE TABLE REQUISITOS_INGRESO (
    REQUISITO_INGRESO_ID SMALLINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    REQUISITO_INGRESO_NOMBRE VARCHAR2(100) NOT NULL,
    REQUISITO_INGRESO_DESCRIPCION VARCHAR2(500),
    CONSTRAINT UK_REQUISITOS_INGRESO UNIQUE (REQUISITO_INGRESO_NOMBRE)
);

CREATE TABLE MODALIDADES (
    MODALIDAD_ID SMALLINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    MODALIDAD_NOMBRE VARCHAR2(15) NOT NULL,
    MODALIDAD_DESCRIPCION VARCHAR2(100),
    CONSTRAINT UK_MODALIDADES UNIQUE (MODALIDAD_NOMBRE)
);

CREATE TABLE JORNADAS (
    JORNADA_ID SMALLINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    JORNADA_NOMBRE VARCHAR2(15) NOT NULL,
    JORNADA_DESCRIPCION VARCHAR2(100),
    CONSTRAINT UK_JORNADAS UNIQUE (JORNADA_NOMBRE)
);

CREATE TABLE TIPOS_PLAN (
    TIPO_PLAN_ID SMALLINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TIPO_PLAN_NOMBRE VARCHAR2(50) NOT NULL,
    TIPO_PLAN_DESCRIPCION VARCHAR2(200),
    CONSTRAINT UK_TIPOS_PLAN UNIQUE (TIPO_PLAN_NOMBRE)
);

CREATE TABLE CARRERAS (
    CARRERA_ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CARRERA_NOMBRE VARCHAR2(100) NOT NULL,
    CARRERA_DESCRIPCION VARCHAR2(500),
    NIVEL_CARRERA_ID SMALLINT NOT NULL,
    REQUISITO_INGRESO_ID SMALLINT NOT NULL,
    MODALIDAD_ID SMALLINT NOT NULL,
    JORNADA_ID SMALLINT NOT NULL,
    TIPO_PLAN_ID SMALLINT NOT NULL,
    AREA_CONOCIMIENTO_ID SMALLINT NOT NULL,
    DURACION_PLAN SMALLINT NOT NULL,
    DURACION_TITULACION SMALLINT NOT NULL,
    DURACION_TOTAL SMALLINT NOT NULL,
    VALORACION_MATRICULA INTEGER NOT NULL,
    VALORACION_ARANCEL INTEGER NOT NULL
);

-- UNIVERSITY / COLLEGE / INSTITUTION RELATED TABLES
CREATE TABLE TIPOS_ACREDITACION (
    TIPO_ACREDITACION_ID SMALLINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ESTADO_ACREDITACION NUMBER(1) DEFAULT 1 CHECK (ESTADO_ACREDITACION IN (0, 1, -1)),
    TIPO_ACREDITACION_DESCRIPCION VARCHAR2(200),
    CONSTRAINT UK_TIPOS_ACREDITACION UNIQUE (ESTADO_ACREDITACION)
);

CREATE TABLE TIPOS_INSTITUCION (
    TIPO_INSTITUCION_ID SMALLINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TIPO_INSTITUCION_NOMBRE VARCHAR2(50) NOT NULL,
    TIPO_INSTITUCION_DESCRIPCION VARCHAR2(200),
    CONSTRAINT UK_TIPOS_INSTITUCION UNIQUE (TIPO_INSTITUCION_NOMBRE)
);

CREATE TABLE INSTITUCIONES (
    INSTITUCION_ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    INSTITUCION_NOMBRE VARCHAR2(100) NOT NULL,
    TIPO_INSTITUCION_ID SMALLINT NOT NULL,
    ACREDITACION_ID SMALLINT NOT NULL,
    PERIODO_ACREDITACION_INICIO DATE,
    PERIODO_ACREDITACION_FIN DATE,
    CONSTRAINT UK_INSTITUCION UNIQUE (INSTITUCION_NOMBRE, TIPO_INSTITUCION_ID)
);

-- ENROLLMENT RELATED TABLES
CREATE TABLE VIAS_INGRESO (
    VIA_INGRESO_ID SMALLINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    VIA_INGRESO_NOMBRE VARCHAR2(100) NOT NULL,
    VIA_INGRESO_DESCRIPCION VARCHAR2(200),
    CONSTRAINT UK_VIAS_INGRESO UNIQUE (VIA_INGRESO_NOMBRE)
);

CREATE TABLE RANGOS_EDAD (
    RANGO_EDAD_ID SMALLINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    RANGO_EDAD_DESCRIPCION VARCHAR2(50) NOT NULL,
    EDAD_MINIMA SMALLINT NOT NULL,
    EDAD_MAXIMA SMALLINT NOT NULL,
    CONSTRAINT UK_RANGOS_EDAD UNIQUE (EDAD_MINIMA, EDAD_MAXIMA),
    CONSTRAINT CHK_RANGOS_EDAD CHECK (EDAD_MINIMA >= 0 AND EDAD_MAXIMA >= EDAD_MINIMA)
);

CREATE TABLE GENEROS (
    GENERO_ID SMALLINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    GENERO_NOMBRE VARCHAR2(20) NOT NULL,
    CONSTRAINT UK_GENEROS UNIQUE (GENERO_NOMBRE)
);

CREATE TABLE MATRICULAS (
    MATRICULA_ID INTEGER PRIMARY KEY, -- los datos ya vienen con IDs asignados
    GENERO_ID SMALLINT NOT NULL,
    EDAD SMALLINT NOT NULL,
    RANGO_EDAD_ID SMALLINT NOT NULL,
    ANIO_INGRESO SMALLINT NOT NULL,
    SEMESTRE_INGRESO SMALLINT NOT NULL,
    INSTITUCION_ID SMALLINT NOT NULL,
    CARRERA_ID SMALLINT NOT NULL,
    VIA_INGRESO_ID SMALLINT NOT NULL,
    COMUNA_ID SMALLINT NOT NULL
);

------------------------------------------------------------------------
-- FOREIGN KEY CONSTRAINTS
------------------------------------------------------------------------

-- Location related foreign keys
ALTER TABLE PROVINCIAS ADD CONSTRAINT FK_PROVINCIAS_REGIONES 
    FOREIGN KEY (REGION_ID) REFERENCES REGIONES(REGION_ID);

ALTER TABLE COMUNAS ADD CONSTRAINT FK_COMUNAS_PROVINCIAS 
    FOREIGN KEY (PROVINCIA_ID) REFERENCES PROVINCIAS(PROVINCIA_ID);

ALTER TABLE COMUNAS ADD CONSTRAINT FK_COMUNAS_REGIONES 
    FOREIGN KEY (REGION_ID) REFERENCES REGIONES(REGION_ID);

-- Degree program related foreign keys
ALTER TABLE NIVELES_CARRERA ADD CONSTRAINT FK_NIVELES_CARRERA_TIPOS_EDUCACION 
    FOREIGN KEY (TIPO_EDUCACION_ID) REFERENCES TIPOS_EDUCACION(TIPO_EDUCACION_ID);

ALTER TABLE NIVELES_CARRERA ADD CONSTRAINT FK_NIVELES_CARRERA_NIVELES_FORMACION 
    FOREIGN KEY (NIVEL_FORMACION_ID) REFERENCES NIVELES_FORMACION(NIVEL_FORMACION_ID);

ALTER TABLE CARRERAS ADD CONSTRAINT FK_CARRERAS_NIVELES_CARRERA 
    FOREIGN KEY (NIVEL_CARRERA_ID) REFERENCES NIVELES_CARRERA(NIVEL_CARRERA_ID);

ALTER TABLE CARRERAS ADD CONSTRAINT FK_CARRERAS_REQUISITOS_INGRESO 
    FOREIGN KEY (REQUISITO_INGRESO_ID) REFERENCES REQUISITOS_INGRESO(REQUISITO_INGRESO_ID);

ALTER TABLE CARRERAS ADD CONSTRAINT FK_CARRERAS_MODALIDADES 
    FOREIGN KEY (MODALIDAD_ID) REFERENCES MODALIDADES(MODALIDAD_ID);

ALTER TABLE CARRERAS ADD CONSTRAINT FK_CARRERAS_JORNADAS 
    FOREIGN KEY (JORNADA_ID) REFERENCES JORNADAS(JORNADA_ID);

ALTER TABLE CARRERAS ADD CONSTRAINT FK_CARRERAS_TIPOS_PLAN 
    FOREIGN KEY (TIPO_PLAN_ID) REFERENCES TIPOS_PLAN(TIPO_PLAN_ID);

ALTER TABLE CARRERAS ADD CONSTRAINT FK_CARRERAS_AREAS_CONOCIMIENTO 
    FOREIGN KEY (AREA_CONOCIMIENTO_ID) REFERENCES AREAS_CONOCIMIENTO(AREA_CONOCIMIENTO_ID);

-- Institution related foreign keys
ALTER TABLE INSTITUCIONES ADD CONSTRAINT FK_INSTITUCIONES_TIPOS_INSTITUCION 
    FOREIGN KEY (TIPO_INSTITUCION_ID) REFERENCES TIPOS_INSTITUCION(TIPO_INSTITUCION_ID);

ALTER TABLE INSTITUCIONES ADD CONSTRAINT FK_INSTITUCIONES_TIPOS_ACREDITACION 
    FOREIGN KEY (ACREDITACION_ID) REFERENCES TIPOS_ACREDITACION(TIPO_ACREDITACION_ID);

-- Enrollment related foreign keys
ALTER TABLE MATRICULAS ADD CONSTRAINT FK_MATRICULAS_RANGOS_EDAD 
    FOREIGN KEY (RANGO_EDAD_ID) REFERENCES RANGOS_EDAD(RANGO_EDAD_ID);

ALTER TABLE MATRICULAS ADD CONSTRAINT FK_MATRICULAS_INSTITUCIONES
    FOREIGN KEY (INSTITUCION_ID) REFERENCES INSTITUCIONES(INSTITUCION_ID);

ALTER TABLE MATRICULAS ADD CONSTRAINT FK_MATRICULAS_CARRERAS 
    FOREIGN KEY (CARRERA_ID) REFERENCES CARRERAS(CARRERA_ID);

ALTER TABLE MATRICULAS ADD CONSTRAINT FK_MATRICULAS_VIAS_INGRESO 
    FOREIGN KEY (VIA_INGRESO_ID) REFERENCES VIAS_INGRESO(VIA_INGRESO_ID);

ALTER TABLE MATRICULAS ADD CONSTRAINT FK_MATRICULAS_COMUNAS 
    FOREIGN KEY (COMUNA_ID) REFERENCES COMUNAS(COMUNA_ID);

------------------------------------------------------------------------
-- PERFORMANCE OPTIMIZATION INDEXES
------------------------------------------------------------------------

-- MATRICULAS Table Indexes (Main Fact Table)
-- Primary access patterns: filtering by year/semester, institution, career, demographics
CREATE INDEX IDX_MATRICULAS_ANIO_SEMESTRE ON MATRICULAS (ANIO_INGRESO, SEMESTRE_INGRESO);
CREATE INDEX IDX_MATRICULAS_INSTITUCION ON MATRICULAS (INSTITUCION_ID);
CREATE INDEX IDX_MATRICULAS_CARRERA ON MATRICULAS (CARRERA_ID);
CREATE INDEX IDX_MATRICULAS_GENERO ON MATRICULAS (GENERO_ID);
CREATE INDEX IDX_MATRICULAS_RANGO_EDAD ON MATRICULAS (RANGO_EDAD_ID);
CREATE INDEX IDX_MATRICULAS_VIA_INGRESO ON MATRICULAS (VIA_INGRESO_ID);
CREATE INDEX IDX_MATRICULAS_COMUNA ON MATRICULAS (COMUNA_ID);

-- Composite indexes for common query patterns
CREATE INDEX IDX_MATRICULAS_INST_CARRERA ON MATRICULAS (INSTITUCION_ID, CARRERA_ID);
CREATE INDEX IDX_MATRICULAS_ANIO_GENERO ON MATRICULAS (ANIO_INGRESO, GENERO_ID);
CREATE INDEX IDX_MATRICULAS_CARRERA_GENERO ON MATRICULAS (CARRERA_ID, GENERO_ID);

-- CARRERAS Table Indexes (Dimension Table)
-- Foreign key columns for join optimization
CREATE INDEX IDX_CARRERAS_NIVEL_CARRERA ON CARRERAS (NIVEL_CARRERA_ID);
CREATE INDEX IDX_CARRERAS_REQUISITO_INGRESO ON CARRERAS (REQUISITO_INGRESO_ID);
CREATE INDEX IDX_CARRERAS_MODALIDAD ON CARRERAS (MODALIDAD_ID);
CREATE INDEX IDX_CARRERAS_JORNADA ON CARRERAS (JORNADA_ID);
CREATE INDEX IDX_CARRERAS_TIPO_PLAN ON CARRERAS (TIPO_PLAN_ID);
CREATE INDEX IDX_CARRERAS_AREA_CONOCIMIENTO ON CARRERAS (AREA_CONOCIMIENTO_ID);

-- Composite indexes for career analysis
CREATE INDEX IDX_CARRERAS_MODALIDAD_JORNADA ON CARRERAS (MODALIDAD_ID, JORNADA_ID);
CREATE INDEX IDX_CARRERAS_AREA_NIVEL ON CARRERAS (AREA_CONOCIMIENTO_ID, NIVEL_CARRERA_ID);

-- INSTITUCIONES Table Indexes (Dimension Table)
CREATE INDEX IDX_INSTITUCIONES_TIPO ON INSTITUCIONES (TIPO_INSTITUCION_ID);
CREATE INDEX IDX_INSTITUCIONES_ACREDITACION ON INSTITUCIONES (ACREDITACION_ID);
CREATE INDEX IDX_INSTITUCIONES_PERIODO_ACRED ON INSTITUCIONES (PERIODO_ACREDITACION_INICIO, PERIODO_ACREDITACION_FIN);

-- LOCATION Tables Indexes (Hierarchical Structure)
CREATE INDEX IDX_PROVINCIAS_REGION ON PROVINCIAS (REGION_ID);
CREATE INDEX IDX_COMUNAS_PROVINCIA ON COMUNAS (PROVINCIA_ID);
CREATE INDEX IDX_COMUNAS_REGION ON COMUNAS (REGION_ID);

-- Composite location index for geographic analysis
CREATE INDEX IDX_COMUNAS_REGION_PROVINCIA ON COMUNAS (REGION_ID, PROVINCIA_ID);

-- NIVELES_CARRERA Table Indexes (Classification Table)
CREATE INDEX IDX_NIVELES_CARRERA_TIPO_EDUCACION ON NIVELES_CARRERA (TIPO_EDUCACION_ID);
CREATE INDEX IDX_NIVELES_CARRERA_NIVEL_FORMACION ON NIVELES_CARRERA (NIVEL_FORMACION_ID);

-- RANGOS_EDAD Table Indexes (for age-based queries)
CREATE INDEX IDX_RANGOS_EDAD_MINIMA ON RANGOS_EDAD (EDAD_MINIMA);
CREATE INDEX IDX_RANGOS_EDAD_MAXIMA ON RANGOS_EDAD (EDAD_MAXIMA);

------------------------------------------------------------------------
-- ADDITIONAL PERFORMANCE OPTIMIZATIONS
------------------------------------------------------------------------

-- Update table statistics for optimal query planning
-- (These should be run after data loading)
-- EXEC DBMS_STATS.GATHER_TABLE_STATS(USER, 'MATRICULAS');
-- EXEC DBMS_STATS.GATHER_TABLE_STATS(USER, 'CARRERAS');
-- EXEC DBMS_STATS.GATHER_TABLE_STATS(USER, 'INSTITUCIONES');

-- Consider partitioning MATRICULAS table by ANIO_INGRESO if data volume grows
-- ALTER TABLE MATRICULAS PARTITION BY RANGE (ANIO_INGRESO) (
--   PARTITION P2020 VALUES LESS THAN (2021),
--   PARTITION P2021 VALUES LESS THAN (2022),
--   PARTITION P2022 VALUES LESS THAN (2023),
--   PARTITION PMAX VALUES LESS THAN (MAXVALUE)
-- );

------------------------------------------------------------------------
-- INDEX USAGE MONITORING
------------------------------------------------------------------------

-- Query to monitor index usage (run periodically in production):
-- SELECT 
--   i.index_name,
--   i.table_name,
--   s.used_by_optimizer,
--   s.last_used
-- FROM user_indexes i
-- LEFT JOIN v$object_usage s ON i.index_name = s.index_name
-- WHERE i.table_name IN ('MATRICULAS', 'CARRERAS', 'INSTITUCIONES')
-- ORDER BY s.last_used DESC NULLS LAST;

-- Commit transaction
COMMIT;

-- Re-enable autocommit
SET AUTOCOMMIT ON;
