CREATE TABLE ERROR_LOG (
  LOG_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  SEVERITY VARCHAR2(10),
  SOURCE_OBJ VARCHAR2(100),
  ERROR_MSG VARCHAR2(4000),
  CREATED_AT DATE DEFAULT SYSDATE
);

-- ejemplo
DECLARE
    e_test EXCEPTION;
BEGIN
    RAISE e_test;
EXCEPTION
  WHEN OTHERS THEN
    INSERT INTO ERROR_LOG (SEVERITY, SOURCE_OBJ, ERROR_MSG)
    VALUES('ERROR','BUILD_RESOURCE_PLAN', SQLERRM);
    ROLLBACK;
    RAISE;
END;