-- Capacidades por institución (aulas disponibles, capacidad por aula, docentes disponibles)
CREATE TABLE INSTITUCION_CAPACIDAD (
  INSTITUCION_ID INTEGER PRIMARY KEY,
  TOTAL_AULAS NUMBER DEFAULT 0,
  CAPACIDAD_POR_AULA NUMBER DEFAULT 40,
  DOCENTES_DISPONIBLES NUMBER DEFAULT 0,
  CONSTRAINT FK_CAP_ID_INST FOREIGN KEY (INSTITUCION_ID) REFERENCES INSTITUCIONES(INSTITUCION_ID)
);
