

SET SERVEROUTPUT ON
PROMPT === TEST: trigger statement/row-level demo ===

PROMPT Cleaning previous test data (if any)...
BEGIN
  DELETE FROM MATRICULAS_BATCH_LOG;
  COMMIT;
EXCEPTION
  WHEN OTHERS THEN
    NULL;
END;
/ 

PROMPT Inserting 3 sample matriculas in a single statement (INSERT ALL)...
INSERT ALL
  INTO MATRICULAS (MATRICULA_ID, GENERO_ID, EDAD, RANGO_EDAD_ID, ANIO_INGRESO, SEMESTRE_INGRESO, INSTITUCION_ID, CARRERA_ID, VIA_INGRESO_ID, COMUNA_ID)
  VALUES (9999001, 1, 20, 1, 2021, 1, 1, 1, 1, 1)
  INTO MATRICULAS (MATRICULA_ID, GENERO_ID, EDAD, RANGO_EDAD_ID, ANIO_INGRESO, SEMESTRE_INGRESO, INSTITUCION_ID, CARRERA_ID, VIA_INGRESO_ID, COMUNA_ID)
  VALUES (9999002, 2, 21, 2, 2021, 1, 1, 1, 1, 1)
  INTO MATRICULAS (MATRICULA_ID, GENERO_ID, EDAD, RANGO_EDAD_ID, ANIO_INGRESO, SEMESTRE_INGRESO, INSTITUCION_ID, CARRERA_ID, VIA_INGRESO_ID, COMUNA_ID)
  VALUES (9999003, 1, 22, 3, 2021, 1, 1, 1, 1, 1)
SELECT * FROM DUAL;

COMMIT;

PROMPT Querying MATRICULAS_BATCH_LOG to show statement-level logging...
SELECT * FROM MATRICULAS_BATCH_LOG ORDER BY LOG_ID;

PROMPT Cleaning up test inserts from MATRICULAS (optional)...
DELETE FROM MATRICULAS WHERE MATRICULA_ID BETWEEN 9999001 AND 9999003;
COMMIT;
PROMPT Test completed.