TRUNCATE TABLE AREAS_CONOCIMIENTO;
ALTER TABLE AREAS_CONOCIMIENTO MODIFY AREA_CONOCIMIENTO_ID GENERATED ALWAYS AS IDENTITY (START WITH 1);
INSERT INTO AREAS_CONOCIMIENTO (AREA_CONOCIMIENTO_NOMBRE, AREA_CONOCIMIENTO_DESCRIPCION) VALUES ('Administracion y Comercio', NULL);
INSERT INTO AREAS_CONOCIMIENTO (AREA_CONOCIMIENTO_NOMBRE, AREA_CONOCIMIENTO_DESCRIPCION) VALUES ('Agropecuaria', NULL);
INSERT INTO AREAS_CONOCIMIENTO (AREA_CONOCIMIENTO_NOMBRE, AREA_CONOCIMIENTO_DESCRIPCION) VALUES ('Arte y Arquitectura', NULL);
INSERT INTO AREAS_CONOCIMIENTO (AREA_CONOCIMIENTO_NOMBRE, AREA_CONOCIMIENTO_DESCRIPCION) VALUES ('Ciencias Basicas', NULL);
INSERT INTO AREAS_CONOCIMIENTO (AREA_CONOCIMIENTO_NOMBRE, AREA_CONOCIMIENTO_DESCRIPCION) VALUES ('Ciencias Sociales', NULL);
INSERT INTO AREAS_CONOCIMIENTO (AREA_CONOCIMIENTO_NOMBRE, AREA_CONOCIMIENTO_DESCRIPCION) VALUES ('Derecho', NULL);
INSERT INTO AREAS_CONOCIMIENTO (AREA_CONOCIMIENTO_NOMBRE, AREA_CONOCIMIENTO_DESCRIPCION) VALUES ('Educacion', NULL);
INSERT INTO AREAS_CONOCIMIENTO (AREA_CONOCIMIENTO_NOMBRE, AREA_CONOCIMIENTO_DESCRIPCION) VALUES ('Humanidades', NULL);
INSERT INTO AREAS_CONOCIMIENTO (AREA_CONOCIMIENTO_NOMBRE, AREA_CONOCIMIENTO_DESCRIPCION) VALUES ('Salud', NULL);
INSERT INTO AREAS_CONOCIMIENTO (AREA_CONOCIMIENTO_NOMBRE, AREA_CONOCIMIENTO_DESCRIPCION) VALUES ('Tecnologia', NULL);

SELECT * FROM AREAS_CONOCIMIENTO;