TRUNCATE TABLE GENEROS;
ALTER TABLE GENEROS MODIFY GENERO_ID GENERATED ALWAYS AS IDENTITY (START WITH 1);
INSERT INTO GENEROS (GENERO_NOMBRE) VALUES ('Femenino');
INSERT INTO GENEROS (GENERO_NOMBRE) VALUES ('Masculino');
INSERT INTO GENEROS (GENERO_NOMBRE) VALUES ('Otros');

SELECT * FROM GENEROS;