TRUNCATE TABLE JORNADAS;
ALTER TABLE JORNADAS MODIFY JORNADA_ID GENERATED ALWAYS AS IDENTITY (START WITH 1);
INSERT INTO JORNADAS (JORNADA_NOMBRE, JORNADA_DESCRIPCION) VALUES ('A Distancia', NULL);
INSERT INTO JORNADAS (JORNADA_NOMBRE, JORNADA_DESCRIPCION) VALUES ('Diurno', NULL);
INSERT INTO JORNADAS (JORNADA_NOMBRE, JORNADA_DESCRIPCION) VALUES ('Otro', NULL);
INSERT INTO JORNADAS (JORNADA_NOMBRE, JORNADA_DESCRIPCION) VALUES ('Semipresencial', NULL);
INSERT INTO JORNADAS (JORNADA_NOMBRE, JORNADA_DESCRIPCION) VALUES ('Vespertino', NULL);

SELECT * FROM JORNADAS;