TRUNCATE TABLE MODALIDADES;
ALTER TABLE MODALIDADES MODIFY MODALIDAD_ID GENERATED ALWAYS AS IDENTITY (START WITH 1);
INSERT INTO MODALIDADES (MODALIDAD_NOMBRE, MODALIDAD_DESCRIPCION) VALUES ('No Presencial', NULL);
INSERT INTO MODALIDADES (MODALIDAD_NOMBRE, MODALIDAD_DESCRIPCION) VALUES ('Presencial', NULL);
INSERT INTO MODALIDADES (MODALIDAD_NOMBRE, MODALIDAD_DESCRIPCION) VALUES ('Semipresencial', NULL);

SELECT * FROM MODALIDADES;