TRUNCATE TABLE NIVELES_FORMACION;
ALTER TABLE NIVELES_FORMACION MODIFY NIVEL_FORMACION_ID GENERATED ALWAYS AS IDENTITY (START WITH 1);
INSERT INTO NIVELES_FORMACION (NIVEL_FORMACION_NOMBRE, NIVEL_FORMACION_DESCRIPCION) VALUES ('Postgrado', NULL);
INSERT INTO NIVELES_FORMACION (NIVEL_FORMACION_NOMBRE, NIVEL_FORMACION_DESCRIPCION) VALUES ('Postitulo', NULL);
INSERT INTO NIVELES_FORMACION (NIVEL_FORMACION_NOMBRE, NIVEL_FORMACION_DESCRIPCION) VALUES ('Pregrado', NULL);

SELECT * FROM NIVELES_FORMACION;