TRUNCATE TABLE REQUISITOS_INGRESO;
ALTER TABLE REQUISITOS_INGRESO MODIFY REQUISITO_INGRESO_ID GENERATED ALWAYS AS IDENTITY (START WITH 1);
INSERT INTO REQUISITOS_INGRESO (REQUISITO_INGRESO_NOMBRE, REQUISITO_INGRESO_DESCRIPCION) VALUES ('Educacion Media', NULL);
INSERT INTO REQUISITOS_INGRESO (REQUISITO_INGRESO_NOMBRE, REQUISITO_INGRESO_DESCRIPCION) VALUES ('Licenciatura', NULL);
INSERT INTO REQUISITOS_INGRESO (REQUISITO_INGRESO_NOMBRE, REQUISITO_INGRESO_DESCRIPCION) VALUES ('Magister', NULL);
INSERT INTO REQUISITOS_INGRESO (REQUISITO_INGRESO_NOMBRE, REQUISITO_INGRESO_DESCRIPCION) VALUES ('Tecnico de Nivel Superior', NULL);
INSERT INTO REQUISITOS_INGRESO (REQUISITO_INGRESO_NOMBRE, REQUISITO_INGRESO_DESCRIPCION) VALUES ('Titulo Profesional', NULL);

SELECT * FROM REQUISITOS_INGRESO;