TRUNCATE TABLE TIPOS_INSTITUCION;
ALTER TABLE TIPOS_INSTITUCION MODIFY TIPO_INSTITUCION_ID GENERATED ALWAYS AS IDENTITY (START WITH 1);
INSERT INTO TIPOS_INSTITUCION (TIPO_INSTITUCION_NOMBRE, TIPO_INSTITUCION_DESCRIPCION) VALUES ('Centros de Formacion Tecnica', NULL);
INSERT INTO TIPOS_INSTITUCION (TIPO_INSTITUCION_NOMBRE, TIPO_INSTITUCION_DESCRIPCION) VALUES ('Institutos Profesionales', NULL);
INSERT INTO TIPOS_INSTITUCION (TIPO_INSTITUCION_NOMBRE, TIPO_INSTITUCION_DESCRIPCION) VALUES ('Universidades CRUCH', NULL);
INSERT INTO TIPOS_INSTITUCION (TIPO_INSTITUCION_NOMBRE, TIPO_INSTITUCION_DESCRIPCION) VALUES ('Universidades Privadas', NULL);

SELECT * FROM TIPOS_INSTITUCION;