TRUNCATE TABLE TIPOS_EDUCACION;
ALTER TABLE TIPOS_EDUCACION MODIFY TIPO_EDUCACION_ID GENERATED ALWAYS AS IDENTITY (START WITH 1);
INSERT INTO TIPOS_EDUCACION (TIPO_EDUCACION_NOMBRE, TIPO_EDUCACION_DESCRIPCION) VALUES ('Carreras Profesionales', NULL);
INSERT INTO TIPOS_EDUCACION (TIPO_EDUCACION_NOMBRE, TIPO_EDUCACION_DESCRIPCION) VALUES ('Carreras Tecnicas', NULL);
INSERT INTO TIPOS_EDUCACION (TIPO_EDUCACION_NOMBRE, TIPO_EDUCACION_DESCRIPCION) VALUES ('Doctorado', NULL);
INSERT INTO TIPOS_EDUCACION (TIPO_EDUCACION_NOMBRE, TIPO_EDUCACION_DESCRIPCION) VALUES ('Magister', NULL);
INSERT INTO TIPOS_EDUCACION (TIPO_EDUCACION_NOMBRE, TIPO_EDUCACION_DESCRIPCION) VALUES ('Postitulo', NULL);

SELECT * FROM TIPOS_EDUCACION;