TRUNCATE TABLE TIPOS_PLAN;
ALTER TABLE TIPOS_PLAN MODIFY TIPO_PLAN_ID GENERATED ALWAYS AS IDENTITY (START WITH 1);
INSERT INTO TIPOS_PLAN (TIPO_PLAN_NOMBRE, TIPO_PLAN_DESCRIPCION) VALUES ('Plan Especial', NULL);
INSERT INTO TIPOS_PLAN (TIPO_PLAN_NOMBRE, TIPO_PLAN_DESCRIPCION) VALUES ('Plan Regular', NULL);
INSERT INTO TIPOS_PLAN (TIPO_PLAN_NOMBRE, TIPO_PLAN_DESCRIPCION) VALUES ('Plan Regular de Continuidad', NULL);

SELECT * FROM TIPOS_PLAN;