TRUNCATE TABLE TIPOS_ACREDITACION;
ALTER TABLE TIPOS_ACREDITACION MODIFY TIPO_ACREDITACION_ID GENERATED ALWAYS AS IDENTITY (START WITH 1);
INSERT INTO TIPOS_ACREDITACION (ESTADO_ACREDITACION, TIPO_ACREDITACION_DESCRIPCION) VALUES (1, 'ACREDITADA');
INSERT INTO TIPOS_ACREDITACION (ESTADO_ACREDITACION, TIPO_ACREDITACION_DESCRIPCION) VALUES (0, 'NO ACREDITADA');
INSERT INTO TIPOS_ACREDITACION (ESTADO_ACREDITACION, TIPO_ACREDITACION_DESCRIPCION) VALUES (-1, 'SIN ESPECIFICAR');
SELECT * FROM TIPOS_ACREDITACION;