TRUNCATE TABLE VIAS_INGRESO;
ALTER TABLE VIAS_INGRESO MODIFY VIA_INGRESO_ID GENERATED ALWAYS AS IDENTITY (START WITH 1);
INSERT INTO VIAS_INGRESO (VIA_INGRESO_NOMBRE, VIA_INGRESO_DESCRIPCION) VALUES ('Articulacion de TNS a carrera profesional', NULL);
INSERT INTO VIAS_INGRESO (VIA_INGRESO_NOMBRE, VIA_INGRESO_DESCRIPCION) VALUES ('Cambio Interno', NULL);
INSERT INTO VIAS_INGRESO (VIA_INGRESO_NOMBRE, VIA_INGRESO_DESCRIPCION) VALUES ('Cambio externo', NULL);
INSERT INTO VIAS_INGRESO (VIA_INGRESO_NOMBRE, VIA_INGRESO_DESCRIPCION) VALUES ('Continuidad desde plan comun o Bachillerato.', NULL);
INSERT INTO VIAS_INGRESO (VIA_INGRESO_NOMBRE, VIA_INGRESO_DESCRIPCION) VALUES ('Ingreso Directo (regular)', NULL);
INSERT INTO VIAS_INGRESO (VIA_INGRESO_NOMBRE, VIA_INGRESO_DESCRIPCION) VALUES ('Ingreso a traves de PACE', NULL);
INSERT INTO VIAS_INGRESO (VIA_INGRESO_NOMBRE, VIA_INGRESO_DESCRIPCION) VALUES ('Ingreso a traves de programas de inclusion', NULL);
INSERT INTO VIAS_INGRESO (VIA_INGRESO_NOMBRE, VIA_INGRESO_DESCRIPCION) VALUES ('Ingreso especial para estudiantes extranjeros', NULL);
INSERT INTO VIAS_INGRESO (VIA_INGRESO_NOMBRE, VIA_INGRESO_DESCRIPCION) VALUES ('Ingreso por Reconocimiento de Aprendizajes Previos (RAP)', NULL);
INSERT INTO VIAS_INGRESO (VIA_INGRESO_NOMBRE, VIA_INGRESO_DESCRIPCION) VALUES ('Ingreso por caracteristicas especiales', NULL);
INSERT INTO VIAS_INGRESO (VIA_INGRESO_NOMBRE, VIA_INGRESO_DESCRIPCION) VALUES ('Otras formas de Ingreso', NULL);

SELECT * FROM VIAS_INGRESO;
