------------------------------------------------------------------------
-- DATABASE SCHEMA CREATION SCRIPT
------------------------------------------------------------------------
-- Start transaction
SET AUTOCOMMIT OFF;

-- LOCATION RELATED TABLES
CREATE TABLE REGIONES (
    REGION_ID SMALLINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    REGION_NOMBRE varchar(64) NOT NULL,
    REGION_ORDINAL varchar(4) NOT NULL,
    CONSTRAINT UK_REGIONES UNIQUE (REGION_NOMBRE, REGION_ORDINAL)
);


CREATE TABLE PROVINCIAS (
    PROVINCIA_ID SMALLINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PROVINCIA_NOMBRE varchar(64) NOT NULL,
    REGION_ID SMALLINT NOT NULL,
    CONSTRAINT UK_PROVINCIAS UNIQUE (PROVINCIA_NOMBRE, REGION_ID)
);

CREATE TABLE COMUNAS (
    COMUNA_ID SMALLINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    COMUNA_NOMBRE varchar(64) NOT NULL,
    PROVINCIA_ID SMALLINT NOT NULL,
    REGION_ID SMALLINT NOT NULL,
    CONSTRAINT UK_COMUNAS UNIQUE (COMUNA_NOMBRE, PROVINCIA_ID, REGION_ID)
);


-- DEGREE PROGRAM RELATED TABLES
CREATE TABLE TIPOS_EDUCACION (
    TIPO_EDUCACION_ID SMALLINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TIPO_EDUCACION_NOMBRE VARCHAR2(30) NOT NULL,
    TIPO_EDUCACION_DESCRIPCION VARCHAR2(100),
    CONSTRAINT UK_TIPOS_EDUCACION UNIQUE (TIPO_EDUCACION_NOMBRE)
);

CREATE TABLE NIVELES_FORMACION (
    NIVEL_FORMACION_ID SMALLINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NIVEL_FORMACION_NOMBRE VARCHAR2(20) NOT NULL,
    NIVEL_FORMACION_DESCRIPCION VARCHAR2(100),
    CONSTRAINT UK_NIVELES_FORMACION UNIQUE (NIVEL_FORMACION_NOMBRE)
);

CREATE TABLE NIVELES_CARRERA (
    NIVEL_CARRERA_ID SMALLINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TIPO_EDUCACION_ID SMALLINT NOT NULL,
    NIVEL_FORMACION_ID SMALLINT NOT NULL,
    NIVEL_CARRERA_DESCRIPCION VARCHAR2(100),
    CONSTRAINT UK_NIVELES_CARRERA UNIQUE (TIPO_EDUCACION_ID, NIVEL_FORMACION_ID)
);

CREATE TABLE AREAS_CONOCIMIENTO (
    AREA_CONOCIMIENTO_ID SMALLINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    AREA_CONOCIMIENTO_NOMBRE VARCHAR2(100) NOT NULL,
    AREA_CONOCIMIENTO_DESCRIPCION VARCHAR2(500),
    CONSTRAINT UK_AREAS_CONOCIMIENTO UNIQUE (AREA_CONOCIMIENTO_NOMBRE)
);

CREATE TABLE REQUISITOS_INGRESO (
    REQUISITO_INGRESO_ID SMALLINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    REQUISITO_INGRESO_NOMBRE VARCHAR2(100) NOT NULL,
    REQUISITO_INGRESO_DESCRIPCION VARCHAR2(500),
    CONSTRAINT UK_REQUISITOS_INGRESO UNIQUE (REQUISITO_INGRESO_NOMBRE)
);

CREATE TABLE MODALIDADES (
    MODALIDAD_ID SMALLINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    MODALIDAD_NOMBRE VARCHAR2(15) NOT NULL,
    MODALIDAD_DESCRIPCION VARCHAR2(100),
    CONSTRAINT UK_MODALIDADES UNIQUE (MODALIDAD_NOMBRE)
);

CREATE TABLE JORNADAS (
    JORNADA_ID SMALLINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    JORNADA_NOMBRE VARCHAR2(15) NOT NULL,
    JORNADA_DESCRIPCION VARCHAR2(100),
    CONSTRAINT UK_JORNADAS UNIQUE (JORNADA_NOMBRE)
);

CREATE TABLE TIPOS_PLAN (
    TIPO_PLAN_ID SMALLINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TIPO_PLAN_NOMBRE VARCHAR2(50) NOT NULL,
    TIPO_PLAN_DESCRIPCION VARCHAR2(200),
    CONSTRAINT UK_TIPOS_PLAN UNIQUE (TIPO_PLAN_NOMBRE)
);

CREATE TABLE CARRERAS (
    CARRERA_ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CARRERA_NOMBRE VARCHAR2(100) NOT NULL,
    CARRERA_DESCRIPCION VARCHAR2(500),
    NIVEL_CARRERA_ID SMALLINT NOT NULL,
    REQUISITO_INGRESO_ID SMALLINT NOT NULL,
    MODALIDAD_ID SMALLINT NOT NULL,
    JORNADA_ID SMALLINT NOT NULL,
    TIPO_PLAN_ID SMALLINT NOT NULL,
    AREA_CONOCIMIENTO_ID SMALLINT NOT NULL,
    DURACION_PLAN SMALLINT NOT NULL,
    DURACION_TITULACION SMALLINT NOT NULL,
    DURACION_TOTAL SMALLINT NOT NULL,
    VALORACION_MATRICULA INTEGER NOT NULL,
    VALORACION_ARANCEL INTEGER NOT NULL
);

-- UNIVERSITY / COLLEGE / INSTITUTION RELATED TABLES
CREATE TABLE TIPOS_ACREDITACION (
    TIPO_ACREDITACION_ID SMALLINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ESTADO_ACREDITACION NUMBER(1) DEFAULT 1 CHECK (ESTADO_ACREDITACION IN (0, 1, -1)),
    TIPO_ACREDITACION_DESCRIPCION VARCHAR2(200),
    CONSTRAINT UK_TIPOS_ACREDITACION UNIQUE (ESTADO_ACREDITACION)
);

CREATE TABLE TIPOS_INSTITUCION (
    TIPO_INSTITUCION_ID SMALLINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TIPO_INSTITUCION_NOMBRE VARCHAR2(50) NOT NULL,
    TIPO_INSTITUCION_DESCRIPCION VARCHAR2(200),
    CONSTRAINT UK_TIPOS_INSTITUCION UNIQUE (TIPO_INSTITUCION_NOMBRE)
);

CREATE TABLE INSTITUCIONES (
    INSTITUCION_ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    INSTITUCION_NOMBRE VARCHAR2(100) NOT NULL,
    TIPO_INSTITUCION_ID SMALLINT NOT NULL,
    ACREDITACION_ID SMALLINT NOT NULL,
    PERIODO_ACREDITACION_INICIO DATE,
    PERIODO_ACREDITACION_FIN DATE,
    CONSTRAINT UK_INSTITUCION UNIQUE (INSTITUCION_NOMBRE, TIPO_INSTITUCION_ID)
);

-- ENROLLMENT RELATED TABLES
CREATE TABLE VIAS_INGRESO (
    VIA_INGRESO_ID SMALLINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    VIA_INGRESO_NOMBRE VARCHAR2(100) NOT NULL,
    VIA_INGRESO_DESCRIPCION VARCHAR2(200),
    CONSTRAINT UK_VIAS_INGRESO UNIQUE (VIA_INGRESO_NOMBRE)
);

CREATE TABLE RANGOS_EDAD (
    RANGO_EDAD_ID SMALLINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    RANGO_EDAD_DESCRIPCION VARCHAR2(50) NOT NULL,
    EDAD_MINIMA SMALLINT NOT NULL,
    EDAD_MAXIMA SMALLINT NOT NULL,
    CONSTRAINT UK_RANGOS_EDAD UNIQUE (EDAD_MINIMA, EDAD_MAXIMA),
    CONSTRAINT CHK_RANGOS_EDAD CHECK (EDAD_MINIMA >= 0 AND EDAD_MAXIMA >= EDAD_MINIMA)
);

CREATE TABLE GENEROS (
    GENERO_ID SMALLINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    GENERO_NOMBRE VARCHAR2(20) NOT NULL,
    CONSTRAINT UK_GENEROS UNIQUE (GENERO_NOMBRE)
);

CREATE TABLE MATRICULAS (
    MATRICULA_ID INTEGER PRIMARY KEY,
    GENERO_ID SMALLINT NOT NULL,
    EDAD SMALLINT NOT NULL,
    RANGO_EDAD_ID SMALLINT NOT NULL,
    ANIO_INGRESO SMALLINT NOT NULL,
    SEMESTRE_INGRESO SMALLINT NOT NULL,
    INSTITUCION_ID SMALLINT NOT NULL,
    CARRERA_ID SMALLINT NOT NULL,
    VIA_INGRESO_ID SMALLINT NOT NULL,
    COMUNA_ID SMALLINT NOT NULL,
    CONSTRAINT CHK_MATRICULAS_EDAD CHECK (EDAD >= 15 AND EDAD <= 100),
    CONSTRAINT CHK_MATRICULAS_ANIO CHECK (ANIO_INGRESO >= 2000 AND ANIO_INGRESO <= 2030),
    CONSTRAINT CHK_MATRICULAS_SEMESTRE CHECK (SEMESTRE_INGRESO IN (1, 2))
);

CREATE TABLE PLANES_RECURSOS (
    PLAN_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    INSTITUCION_ID INTEGER,
    INSTITUCION_NOMBRE VARCHAR2(200),
    CARRERA_ID INTEGER,
    CARRERA_NOMBRE VARCHAR2(200),
    SEMESTRE_LABEL VARCHAR2(10) NOT NULL,
    ESTUDIANTES_PROYECTADOS NUMBER DEFAULT 0 CHECK (ESTUDIANTES_PROYECTADOS >= 0),
    PROFERORES_REQUERIDOS NUMBER DEFAULT 0 CHECK (PROFERORES_REQUERIDOS >= 0),
    SALAS_REQUERIDAS NUMBER DEFAULT 0 CHECK (SALAS_REQUERIDAS >= 0),
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
    UPDATED_AT DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT CHK_PLANES_RECURSOS_SEMESTRE CHECK (SEMESTRE_LABEL IN ('2024-1', '2024-2', '2025-1', '2025-2', '2026-1', '2026-2', '2027-1', '2027-2')),
    CONSTRAINT CHK_PLANES_RECURSOS_LOGIC CHECK (
        (INSTITUCION_ID IS NOT NULL OR INSTITUCION_NOMBRE IS NOT NULL) AND
        (CARRERA_ID IS NOT NULL OR CARRERA_NOMBRE IS NOT NULL)
    )
);

CREATE TABLE ERROR_LOG (
    LOG_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    SEVERITY VARCHAR2(10) DEFAULT 'INFO' NOT NULL,
    SOURCE_OBJ VARCHAR2(100) NOT NULL,
    ERROR_MSG VARCHAR2(4000) NOT NULL,
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT CHK_ERROR_LOG_SEVERITY CHECK (SEVERITY IN ('DEBUG', 'INFO', 'WARN', 'ERROR', 'FATAL'))
);

CREATE TABLE INSTITUCION_CAPACIDAD (
  INSTITUCION_ID INTEGER PRIMARY KEY,
  TOTAL_AULAS NUMBER DEFAULT 0 NOT NULL,
  CAPACIDAD_POR_AULA NUMBER DEFAULT 40 NOT NULL,
  DOCENTES_DISPONIBLES NUMBER DEFAULT 0 NOT NULL,
  CONSTRAINT FK_CAP_ID_INST FOREIGN KEY (INSTITUCION_ID) REFERENCES INSTITUCIONES(INSTITUCION_ID),
  CONSTRAINT CHK_INST_CAP_AULAS CHECK (TOTAL_AULAS >= 0),
  CONSTRAINT CHK_INST_CAP_CAPACIDAD CHECK (CAPACIDAD_POR_AULA > 0 AND CAPACIDAD_POR_AULA <= 500),
  CONSTRAINT CHK_INST_CAP_DOCENTES CHECK (DOCENTES_DISPONIBLES >= 0)
);

------------------------------------------------------------------------
-- FOREIGN KEY CONSTRAINTS
------------------------------------------------------------------------

-- Location related foreign keys
ALTER TABLE PROVINCIAS ADD CONSTRAINT FK_PROVINCIAS_REGIONES 
    FOREIGN KEY (REGION_ID) REFERENCES REGIONES(REGION_ID);

ALTER TABLE COMUNAS ADD CONSTRAINT FK_COMUNAS_PROVINCIAS 
    FOREIGN KEY (PROVINCIA_ID) REFERENCES PROVINCIAS(PROVINCIA_ID);

ALTER TABLE COMUNAS ADD CONSTRAINT FK_COMUNAS_REGIONES 
    FOREIGN KEY (REGION_ID) REFERENCES REGIONES(REGION_ID);

-- Degree program related foreign keys
ALTER TABLE NIVELES_CARRERA ADD CONSTRAINT FK_NIVELES_CARRERA_TIPOS_EDUCACION 
    FOREIGN KEY (TIPO_EDUCACION_ID) REFERENCES TIPOS_EDUCACION(TIPO_EDUCACION_ID);

ALTER TABLE NIVELES_CARRERA ADD CONSTRAINT FK_NIVELES_CARRERA_NIVELES_FORMACION 
    FOREIGN KEY (NIVEL_FORMACION_ID) REFERENCES NIVELES_FORMACION(NIVEL_FORMACION_ID);

ALTER TABLE CARRERAS ADD CONSTRAINT FK_CARRERAS_NIVELES_CARRERA 
    FOREIGN KEY (NIVEL_CARRERA_ID) REFERENCES NIVELES_CARRERA(NIVEL_CARRERA_ID);

ALTER TABLE CARRERAS ADD CONSTRAINT FK_CARRERAS_REQUISITOS_INGRESO 
    FOREIGN KEY (REQUISITO_INGRESO_ID) REFERENCES REQUISITOS_INGRESO(REQUISITO_INGRESO_ID);

ALTER TABLE CARRERAS ADD CONSTRAINT FK_CARRERAS_MODALIDADES 
    FOREIGN KEY (MODALIDAD_ID) REFERENCES MODALIDADES(MODALIDAD_ID);

ALTER TABLE CARRERAS ADD CONSTRAINT FK_CARRERAS_JORNADAS 
    FOREIGN KEY (JORNADA_ID) REFERENCES JORNADAS(JORNADA_ID);

ALTER TABLE CARRERAS ADD CONSTRAINT FK_CARRERAS_TIPOS_PLAN 
    FOREIGN KEY (TIPO_PLAN_ID) REFERENCES TIPOS_PLAN(TIPO_PLAN_ID);

ALTER TABLE CARRERAS ADD CONSTRAINT FK_CARRERAS_AREAS_CONOCIMIENTO 
    FOREIGN KEY (AREA_CONOCIMIENTO_ID) REFERENCES AREAS_CONOCIMIENTO(AREA_CONOCIMIENTO_ID);

-- Institution related foreign keys
ALTER TABLE INSTITUCIONES ADD CONSTRAINT FK_INSTITUCIONES_TIPOS_INSTITUCION 
    FOREIGN KEY (TIPO_INSTITUCION_ID) REFERENCES TIPOS_INSTITUCION(TIPO_INSTITUCION_ID);

ALTER TABLE INSTITUCIONES ADD CONSTRAINT FK_INSTITUCIONES_TIPOS_ACREDITACION 
    FOREIGN KEY (ACREDITACION_ID) REFERENCES TIPOS_ACREDITACION(TIPO_ACREDITACION_ID);

-- Enrollment related foreign keys
ALTER TABLE MATRICULAS ADD CONSTRAINT FK_MATRICULAS_RANGOS_EDAD 
    FOREIGN KEY (RANGO_EDAD_ID) REFERENCES RANGOS_EDAD(RANGO_EDAD_ID);

ALTER TABLE MATRICULAS ADD CONSTRAINT FK_MATRICULAS_INSTITUCIONES
    FOREIGN KEY (INSTITUCION_ID) REFERENCES INSTITUCIONES(INSTITUCION_ID);

ALTER TABLE MATRICULAS ADD CONSTRAINT FK_MATRICULAS_CARRERAS 
    FOREIGN KEY (CARRERA_ID) REFERENCES CARRERAS(CARRERA_ID);

ALTER TABLE MATRICULAS ADD CONSTRAINT FK_MATRICULAS_VIAS_INGRESO 
    FOREIGN KEY (VIA_INGRESO_ID) REFERENCES VIAS_INGRESO(VIA_INGRESO_ID);

ALTER TABLE MATRICULAS ADD CONSTRAINT FK_MATRICULAS_COMUNAS 
    FOREIGN KEY (COMUNA_ID) REFERENCES COMUNAS(COMUNA_ID);

ALTER TABLE MATRICULAS ADD CONSTRAINT FK_MATRICULAS_GENEROS 
    FOREIGN KEY (GENERO_ID) REFERENCES GENEROS(GENERO_ID);

-- New tables foreign keys
ALTER TABLE PLANES_RECURSOS ADD CONSTRAINT FK_PLANES_RECURSOS_INSTITUCIONES 
    FOREIGN KEY (INSTITUCION_ID) REFERENCES INSTITUCIONES(INSTITUCION_ID);

ALTER TABLE PLANES_RECURSOS ADD CONSTRAINT FK_PLANES_RECURSOS_CARRERAS 
    FOREIGN KEY (CARRERA_ID) REFERENCES CARRERAS(CARRERA_ID);

------------------------------------------------------------------------
-- PERFORMANCE OPTIMIZATION INDEXES
------------------------------------------------------------------------

-- MATRICULAS Table Indexes (Main Fact Table)
-- Primary access patterns: filtering by year/semester, institution, career, demographics
CREATE INDEX IDX_MATRICULAS_ANIO_SEMESTRE ON MATRICULAS (ANIO_INGRESO, SEMESTRE_INGRESO);
CREATE INDEX IDX_MATRICULAS_INSTITUCION ON MATRICULAS (INSTITUCION_ID);
CREATE INDEX IDX_MATRICULAS_CARRERA ON MATRICULAS (CARRERA_ID);
CREATE INDEX IDX_MATRICULAS_GENERO ON MATRICULAS (GENERO_ID);
CREATE INDEX IDX_MATRICULAS_RANGO_EDAD ON MATRICULAS (RANGO_EDAD_ID);
CREATE INDEX IDX_MATRICULAS_VIA_INGRESO ON MATRICULAS (VIA_INGRESO_ID);
CREATE INDEX IDX_MATRICULAS_COMUNA ON MATRICULAS (COMUNA_ID);

-- Composite indexes for common query patterns
CREATE INDEX IDX_MATRICULAS_INST_CARRERA ON MATRICULAS (INSTITUCION_ID, CARRERA_ID);
CREATE INDEX IDX_MATRICULAS_ANIO_GENERO ON MATRICULAS (ANIO_INGRESO, GENERO_ID);
CREATE INDEX IDX_MATRICULAS_CARRERA_GENERO ON MATRICULAS (CARRERA_ID, GENERO_ID);
CREATE INDEX IDX_MATRICULAS_ANIO_SEM_INST ON MATRICULAS (ANIO_INGRESO, SEMESTRE_INGRESO, INSTITUCION_ID);
CREATE INDEX IDX_MATRICULAS_COMUNA_CARRERA ON MATRICULAS (COMUNA_ID, CARRERA_ID);
CREATE INDEX IDX_MATRICULAS_VIA_INGRESO_ANIO ON MATRICULAS (VIA_INGRESO_ID, ANIO_INGRESO);

-- CARRERAS Table Indexes (Dimension Table)
-- Foreign key columns for join optimization
CREATE INDEX IDX_CARRERAS_NIVEL_CARRERA ON CARRERAS (NIVEL_CARRERA_ID);
CREATE INDEX IDX_CARRERAS_REQUISITO_INGRESO ON CARRERAS (REQUISITO_INGRESO_ID);
CREATE INDEX IDX_CARRERAS_MODALIDAD ON CARRERAS (MODALIDAD_ID);
CREATE INDEX IDX_CARRERAS_JORNADA ON CARRERAS (JORNADA_ID);
CREATE INDEX IDX_CARRERAS_TIPO_PLAN ON CARRERAS (TIPO_PLAN_ID);
CREATE INDEX IDX_CARRERAS_AREA_CONOCIMIENTO ON CARRERAS (AREA_CONOCIMIENTO_ID);

-- Composite indexes for career analysis
CREATE INDEX IDX_CARRERAS_MODALIDAD_JORNADA ON CARRERAS (MODALIDAD_ID, JORNADA_ID);
CREATE INDEX IDX_CARRERAS_AREA_NIVEL ON CARRERAS (AREA_CONOCIMIENTO_ID, NIVEL_CARRERA_ID);

-- INSTITUCIONES Table Indexes (Dimension Table)
CREATE INDEX IDX_INSTITUCIONES_TIPO ON INSTITUCIONES (TIPO_INSTITUCION_ID);
CREATE INDEX IDX_INSTITUCIONES_ACREDITACION ON INSTITUCIONES (ACREDITACION_ID);
CREATE INDEX IDX_INSTITUCIONES_PERIODO_ACRED ON INSTITUCIONES (PERIODO_ACREDITACION_INICIO, PERIODO_ACREDITACION_FIN);

-- LOCATION Tables Indexes (Hierarchical Structure)
CREATE INDEX IDX_PROVINCIAS_REGION ON PROVINCIAS (REGION_ID);
CREATE INDEX IDX_COMUNAS_PROVINCIA ON COMUNAS (PROVINCIA_ID);
CREATE INDEX IDX_COMUNAS_REGION ON COMUNAS (REGION_ID);

-- Composite location index for geographic analysis
CREATE INDEX IDX_COMUNAS_REGION_PROVINCIA ON COMUNAS (REGION_ID, PROVINCIA_ID);

-- NIVELES_CARRERA Table Indexes (Classification Table)
CREATE INDEX IDX_NIVELES_CARRERA_TIPO_EDUCACION ON NIVELES_CARRERA (TIPO_EDUCACION_ID);
CREATE INDEX IDX_NIVELES_CARRERA_NIVEL_FORMACION ON NIVELES_CARRERA (NIVEL_FORMACION_ID);

-- RANGOS_EDAD Table Indexes (for age-based queries)
CREATE INDEX IDX_RANGOS_EDAD_MINIMA ON RANGOS_EDAD (EDAD_MINIMA);
CREATE INDEX IDX_RANGOS_EDAD_MAXIMA ON RANGOS_EDAD (EDAD_MAXIMA);

-- PLANES_RECURSOS Table Indexes (Resource Planning Table)
CREATE INDEX IDX_PLANES_RECURSOS_INSTITUCION ON PLANES_RECURSOS (INSTITUCION_ID);
CREATE INDEX IDX_PLANES_RECURSOS_CARRERA ON PLANES_RECURSOS (CARRERA_ID);
CREATE INDEX IDX_PLANES_RECURSOS_SEMESTRE ON PLANES_RECURSOS (SEMESTRE_LABEL);
CREATE INDEX IDX_PLANES_RECURSOS_CREATED_AT ON PLANES_RECURSOS (CREATED_AT);
CREATE INDEX IDX_PLANES_RECURSOS_UPDATED_AT ON PLANES_RECURSOS (UPDATED_AT);

-- Composite indexes for resource planning queries
CREATE INDEX IDX_PLANES_RECURSOS_INST_CARRERA ON PLANES_RECURSOS (INSTITUCION_ID, CARRERA_ID);
CREATE INDEX IDX_PLANES_RECURSOS_SEM_CREATED ON PLANES_RECURSOS (SEMESTRE_LABEL, CREATED_AT);

-- ERROR_LOG Table Indexes (System Monitoring Table)
CREATE INDEX IDX_ERROR_LOG_SEVERITY ON ERROR_LOG (SEVERITY);
CREATE INDEX IDX_ERROR_LOG_SOURCE_OBJ ON ERROR_LOG (SOURCE_OBJ);
CREATE INDEX IDX_ERROR_LOG_CREATED_AT ON ERROR_LOG (CREATED_AT);

-- Composite indexes for error analysis
CREATE INDEX IDX_ERROR_LOG_SEV_SOURCE ON ERROR_LOG (SEVERITY, SOURCE_OBJ);
CREATE INDEX IDX_ERROR_LOG_SEV_CREATED ON ERROR_LOG (SEVERITY, CREATED_AT);

-- GENEROS Table Index (Dimension Table)
-- Note: No additional indexes needed as it's a small lookup table with unique constraint

-- INSTITUCION_CAPACIDAD Table Indexes (Capacity Planning Table)
-- Since this is a 1:1 relationship with INSTITUCIONES and uses INSTITUCION_ID as PK,
-- additional indexes are generally not needed for the primary key field.
-- However, we can add indexes for capacity-based queries:
CREATE INDEX IDX_INST_CAP_TOTAL_AULAS ON INSTITUCION_CAPACIDAD (TOTAL_AULAS);
CREATE INDEX IDX_INST_CAP_DOCENTES ON INSTITUCION_CAPACIDAD (DOCENTES_DISPONIBLES);
CREATE INDEX IDX_INST_CAP_CAPACIDAD_AULA ON INSTITUCION_CAPACIDAD (CAPACIDAD_POR_AULA);

-- Composite index for capacity planning calculations
CREATE INDEX IDX_INST_CAP_PLANNING ON INSTITUCION_CAPACIDAD (TOTAL_AULAS, CAPACIDAD_POR_AULA, DOCENTES_DISPONIBLES);

------------------------------------------------------------------------
-- ADDITIONAL PERFORMANCE OPTIMIZATIONS
------------------------------------------------------------------------

-- Update table statistics for optimal query planning
-- (These should be run after data loading)
-- EXEC DBMS_STATS.GATHER_TABLE_STATS(USER, 'MATRICULAS');
-- EXEC DBMS_STATS.GATHER_TABLE_STATS(USER, 'CARRERAS');
-- EXEC DBMS_STATS.GATHER_TABLE_STATS(USER, 'INSTITUCIONES');
-- EXEC DBMS_STATS.GATHER_TABLE_STATS(USER, 'INSTITUCION_CAPACIDAD');
-- EXEC DBMS_STATS.GATHER_TABLE_STATS(USER, 'PLANES_RECURSOS');

-- Consider partitioning MATRICULAS table by ANIO_INGRESO if data volume grows
-- ALTER TABLE MATRICULAS PARTITION BY RANGE (ANIO_INGRESO) (
--   PARTITION P2020 VALUES LESS THAN (2021),
--   PARTITION P2021 VALUES LESS THAN (2022),
--   PARTITION P2022 VALUES LESS THAN (2023),
--   PARTITION PMAX VALUES LESS THAN (MAXVALUE)
-- );

------------------------------------------------------------------------
-- INDEX USAGE MONITORING
------------------------------------------------------------------------

-- Query to monitor index usage (run periodically in production):
-- SELECT 
--   i.index_name,
--   i.table_name,
--   s.used_by_optimizer,
--   s.last_used
-- FROM user_indexes i
-- LEFT JOIN v$object_usage s ON i.index_name = s.index_name
-- WHERE i.table_name IN ('MATRICULAS', 'CARRERAS', 'INSTITUCIONES')
-- ORDER BY s.last_used DESC NULLS LAST;

-- Commit transaction
COMMIT;

------------------------------------------------------------------------
-- TRIGGERS FOR AUTOMATED UPDATES
------------------------------------------------------------------------

-- Trigger to automatically update UPDATED_AT timestamp in PLANES_RECURSOS
CREATE OR REPLACE TRIGGER TRG_PLANES_RECURSOS_UPDATED_AT
    BEFORE UPDATE ON PLANES_RECURSOS
    FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := SYSDATE;
END;
/

------------------------------------------------------------------------
-- DATA CLEANUP AND MAINTENANCE PROCEDURES
------------------------------------------------------------------------

-- Create a procedure to clean old error logs (keep last 30 days)
CREATE OR REPLACE PROCEDURE CLEAN_ERROR_LOGS(
    p_days_to_keep NUMBER DEFAULT 30
) AS
BEGIN
    DELETE FROM ERROR_LOG 
    WHERE CREATED_AT < SYSDATE - p_days_to_keep
    AND SEVERITY IN ('DEBUG', 'INFO');
    
    COMMIT;
    
    DBMS_OUTPUT.PUT_LINE('Cleaned ' || SQL%ROWCOUNT || ' old log entries');
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END;
/

-- Re-enable autocommit
SET AUTOCOMMIT ON;
